format: alps-port-v1
name: plasma-setup
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: plasma-setup-6.7.4
tarball: plasma-setup-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/plasma-setup-6.7.4.tar.xz
md5: 001cae1a7e6326074643dde0f097498e
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 56
book_order: 578057
