format: alps-port-v1
name: obconf-qt
version: 0.16.6
page_kind: single_package
section: lxqt
page: obconf-qt
title: obconf-qt-0.16.6
tarball: obconf-qt-0.16.6.tar.xz
url: https://github.com/lxqt/obconf-qt/releases/download/0.16.6/obconf-qt-0.16.6.tar.xz
md5: 24eb56d0aac8099cbceeff412d82c4c9
summary: The obconf-qt package is a Qt-based configuration tool for Openbox.
download_size: 128 KB
disk_space: 6.7 MB
sbu: 0.2 SBU
depends:
  required:
  - hicolor-icon-theme
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 709000
