format: alps-port-v1
name: x264
version: '20250815'
page_kind: single_package
section: multimedia
page: x264
title: x264-20250815
tarball: x264-20250815.tar.xz
url: https://anduin.linuxfromscratch.org/BLFS/x264/x264-20250815.tar.xz
md5: a4adb6f7d2644043765885e54abc3955
summary: x264 package provides a library for encoding video streams into the H.264/MPEG-4
  AVC format.
download_size: 732 KB
disk_space: 15 MB
sbu: 0.2 SBU (Using parallelism=4)
depends:
  required: []
  recommended:
  - nasm
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 806000
