format: alps-port-v1
name: sassc
version: 3.6.2
page_kind: multi_package
section: general
page: sassc
title: sassc-3.6.2
tarball: sassc-3.6.2.tar.gz
url: https://github.com/sass/sassc/archive/3.6.2/sassc-3.6.2.tar.gz
md5: 4c3b06ce2979f2a9f0a35093e501d8bb
summary: SassC is a wrapper around libsass, a CSS pre-processor language.
download_size: 28 KB
disk_space: 5.1 MB
sbu: less than 0.1 SBU
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: additional download
  url: https://github.com/sass/libsass/archive/3.6.6/libsass-3.6.6.tar.gz
  filename: libsass-3.6.6.tar.gz
  md5: afda97284d75a030cabadf5b9f998a3b
book_order: 248000
