format: alps-port-v1
name: datetime-format-strptime
version: '1.80'
page_kind: perl_module
section: general
page: perl-deps
title: DateTime::Format::Strptime-1.80
tarball: DateTime-Format-Strptime-1.80.tar.gz
url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.80.tar.gz
md5: 574119fab01ef37082c002d237140009
summary: DateTime::Format::Strptime implements most of strptime(3), i.e. it takes
  a string and a pattern and returns a DateTime object.
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - datetime
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 340000
