format: alps-port-v1
name: libassuan
version: 3.0.2
page_kind: single_package
section: general
page: libassuan
title: libassuan-3.0.2
tarball: libassuan-3.0.2.tar.bz2
url: https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.2.tar.bz2
md5: c6f1bf4bd2aaa79cd1635dcc070ba51a
summary: The libassuan package contains an inter process communication library used
  by some of the other GnuPG related packages. libassuan's primary use is to allow
  a client to interact with a non-persistent server. libassuan is not, however, limited
  to use with GnuPG servers and clients. It was designed to be flexible enough to
  meet the demands of many transaction based environments with non-persistent se
download_size: 580 KB
disk_space: 6.5 MB (with tests, add 3.4 MB for pdf documentation)
sbu: 0.1 SBU (with tests and html documentation)
depends:
  required:
  - libgpg-error
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 134000
