format: alps-port-v1
name: libmbim
version: 1.34.0
page_kind: single_package
section: general
page: libmbim
title: libmbim-1.34.0
tarball: libmbim-1.34.0.tar.gz
url: https://gitlab.freedesktop.org/mobile-broadband/libmbim/-/archive/1.34.0/libmbim-1.34.0.tar.gz
md5: e5c2b38c6a79a047b93cb0c9510bd91f
summary: The libmbim package contains a GLib-based library for talking to WWAN modems
  and devices which speak the Mobile Interface Broadband Model (MBIM) protocol.
download_size: 292 KB
disk_space: 23 MB (with tests)
sbu: 0.2 SBU (with tests)
depends:
  required: []
  recommended:
  - glib
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 153000
