format: alps-port-v1
name: xsoft
version: '0'
page_kind: configuration
section: xsoft
page: xsoft
title: X Software
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 720000
