format: alps-port-v1
name: lxqt-libkscreen
version: 6.7.4
page_kind: single_package
section: lxqt
page: lxqt-libkscreen
title: libkscreen-6.7.4 for lxqt
tarball: libkscreen-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/libkscreen-6.7.4.tar.xz
md5: 227422d0896d13924d99a74707b3e05c
summary: The libkscreen package contains the KDE Screen Management library.
download_size: 118 KB
disk_space: 18 MB
sbu: 0.3 SBU (using parallelism=4)
depends:
  required:
  - kwayland-6.7.4-for-lxqt
  - plasma-wayland-protocols
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 680000
