format: alps-port-v1
name: meta-networking-tools
version: '1'
page_kind: meta
section: meta
page: meta-networking-tools
title: meta-networking-tools
tarball: ''
url: ''
md5: ''
summary: Common networking clients/tools (wget, curl, …)
depends:
  required: []
  recommended: []
members:
- curl
- iw
- nmap
- rsync
- traceroute
- wget
- whois
- wireless-tools
bootscripts: []
provides: []
conflicts: []
book_order: 10002170
