format: alps-port-v1
name: vlc
version: 3.0.23
page_kind: single_package
section: multimedia
page: vlc
title: VLC-3.0.23
tarball: vlc-3.0.23.tar.xz
url: https://download.videolan.org/vlc/3.0.23/vlc-3.0.23.tar.xz
md5: ebc3f0d0a94785fd2b2df4087516938e
summary: VLC is a media player, streamer, and encoder. It can play from many inputs,
  such as files, network streams, capture devices, desktops, or DVD, SVCD, VCD, and
  audio CD. It can use most audio and video codecs (MPEG 1/2/4, H264, VC-1, DivX,
  WMV, Vorbis, AC3, AAC, etc.), and it can also convert to different formats and/or
  send streams through the network.
download_size: 26 MB
disk_space: 957 MB
sbu: 1.2 SBU (using parallelism=4; with tests)
depends:
  required: []
  recommended:
  - alsa-lib
  - desktop-file-utils
  - liba52
  - libgcrypt
  - libmad
  - qt
  - a-graphical-environment
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 822000
