format: alps-port-v1
name: pst
version: '0'
page_kind: configuration
section: pst
page: pst
title: Printing, Scanning and Typesetting
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 831000
