format: alps-port-v1
name: plasma-workspace
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: plasma-workspace-6.7.4
tarball: plasma-workspace-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/plasma-workspace-6.7.4.tar.xz
md5: 05560389f2f05f669e009c2fd0ebe59f
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - extra-cmake-modules
  - qt
  - meta-frameworks6
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 19
book_order: 578020
