format: alps-port-v1
name: atkmm
version: 2.28.5
page_kind: single_package
section: x
page: atkmm
title: Atkmm-2.28.5
tarball: atkmm-2.28.5.tar.xz
url: https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.5.tar.xz
md5: c9bdc196eed368c274177b0c1caf140c
summary: Atkmm is the official C++ interface for the ATK accessibility toolkit library.
download_size: 596 KB
disk_space: 11 MB
sbu: 0.2 SBU
depends:
  required:
  - at-spi2-core
  - glibmm
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 472000
