format: alps-port-v1
name: libpaper
version: 2.2.8
page_kind: single_package
section: general
page: libpaper
title: libpaper-2.2.8
tarball: libpaper-2.2.8.tar.gz
url: https://github.com/rrthomas/libpaper/releases/download/v2.2.8/libpaper-2.2.8.tar.gz
md5: 6ec14207927c291631062338e148bf27
summary: This package is intended to provide a simple way for applications to take
  actions based on a system or user-specified paper size.
download_size: 1.3 MB
disk_space: 12 MB (with tests)
sbu: 0.1 SBU (with tests)
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 155000
