format: alps-port-v1
name: meta-kde
version: '1'
page_kind: meta
section: meta
page: meta-kde
title: meta-kde
tarball: ''
url: ''
md5: ''
summary: 'Meta-package: install BLFS ports from section ''kde'''
depends:
  required: []
  recommended: []
  ignore_for_order: []
members:
- ark
- attica
- aurorae
- baloo
- bluedevil
- bluez-qt
- bolt
- breeze
- breeze-gtk
- corrosion
- dolphin
- dolphin-plugins
- drkonqi
- extra-cmake-modules
- frameworkintegration
- gwenview
- k3b
- kactivitymanagerd
- kapidox
- karchive
- kauth
- kbookmarks
- kcalendarcore
- kcmutils
- kcodecs
- kcolorscheme
- kcompletion
- kconfig
- kconfigwidgets
- kcontacts
- kcoreaddons
- kcrash
- kdav
- kdbusaddons
- kddockwidgets
- kde-cli-tools
- kde-gtk-config
- kdeclarative
- kdecoration
- kded
- kdenlive
- kdeplasma-addons
- kdesu
- kdnssd
- kdoctools
- kfilemetadata
- kgamma
- kglobalaccel
- kglobalacceld
- kguiaddons
- khelpcenter
- kholidays
- ki18n
- kiconthemes
- kidletime
- kimageformats
- kinfocenter
- kio
- kio-extras
- kirigami
- kirigami-addons
- kitemmodels
- kitemviews
- kjobwidgets
- kmenuedit
- kmime
- kmix
- knewstuff
- knighttime
- knotifications
- knotifyconfig
- konsole
- konversation
- kpackage
- kparts
- kpeople
- kpipewire
- kplotting
- kpty
- kquickcharts
- kquickimageeditor
- krunner
- kscreen
- kscreenlocker
- kservice
- ksshaskpass
- kstatusnotifieritem
- ksvg
- ksystemstats
- ktexteditor
- ktexttemplate
- ktextwidgets
- kunitconversion
- kuserfeedback
- kwallet
- kwallet-pam
- kwayland
- kwidgetsaddons
- kwin
- kwin-x11
- kwindowsystem
- kwrited
- kxmlgui
- layer-shell-qt
- leptonica
- libdmtx
- libkcddb
- libkdcraw
- libkexiv2
- libkscreen
- libksysguard
- libplasma
- milou
- modemmanager-qt
- networkmanager-qt
- ocean-sound-theme
- okular
- oxygen
- oxygen-sounds
- phonon
- phonon-backend-vlc
- plasma-activities
- plasma-activities-stats
- plasma-desktop
- plasma-disks
- plasma-firewall
- plasma-integration
- plasma-keyboard
- plasma-nm
- plasma-pa
- plasma-setup
- plasma-systemmonitor
- plasma-thunderbolt
- plasma-vault
- plasma-wayland-protocols
- plasma-welcome
- plasma-workspace
- plasma-workspace-wallpapers
- plasma5support
- polkit-kde-agent-1
- polkit-qt
- powerdevil
- print-manager
- prison
- pulseaudio-qt
- purpose
- qqc2-breeze-style
- qqc2-desktop-style
- qtkeychain
- sddm-kcm
- solid
- sonnet
- spectacle
- syndication
- syntax-highlighting
- systemsettings
- tesseract
- threadweaver
- wacomtablet
- xdg-desktop-portal-kde
bootscripts: []
provides: []
conflicts: []
book_order: 10000776
