format: alps-port-v1
name: seatd
version: 0.9.3
page_kind: single_package
section: general
page: seatd
title: seatd-0.9.3
tarball: seatd-0.9.3.tar.gz
url: https://github.com/kennylevinsen/seatd/archive/0.9.3/seatd-0.9.3.tar.gz
md5: c1cc200188d31214b88af015b1f19f7b
summary: The seatd package provides a universal seat management library. It is what
  a lot of Wayland compositors use to manage seats, a session for a user in which
  applications can interact with. It can optionally provide its own seat manager as
  an alternative to a logind variant, but the instructions provided will use it as
  a shim, which logind from Systemd-261.2 will be the underlying seat manager.
download_size: 44 KB
disk_space: 4 MB (with tests)
sbu: less than 0.1 SBU (with tests)
depends:
  required: []
  recommended:
  - systemd
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 304000
