format: alps-port-v1
name: nspr
version: '4.40'
page_kind: single_package
section: general
page: nspr
title: NSPR-4.40
tarball: nspr-4.40.tar.gz
url: https://archive.mozilla.org/pub/nspr/releases/v4.40/src/nspr-4.40.tar.gz
md5: 0c3c871158cc9af694f1f7d2b799ffd8
summary: Netscape Portable Runtime (NSPR) provides a platform-neutral API for system
  level and libc like functions.
download_size: 988 KB
disk_space: 11 MB
sbu: less than 0.1 SBU
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 185000
