format: alps-port-v1
name: test-leaktrace
version: '0.17'
page_kind: perl_module
section: general
page: perl-deps
title: Test::LeakTrace-0.17
tarball: Test-LeakTrace-0.17.tar.gz
url: https://cpan.metacpan.org/authors/id/L/LE/LEEJO/Test-LeakTrace-0.17.tar.gz
md5: afdb2cc6be0807cb635fb601a004d522
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 340000
