format: alps-port-v1
name: xorg-evdev-driver
version: 2.11.0
page_kind: x11_driver
section: x
page: x7driver
title: Xorg Evdev Driver-2.11.0
tarball: xf86-input-evdev-2.11.0.tar.xz
url: https://www.x.org/pub/individual/driver/xf86-input-evdev-2.11.0.tar.xz
md5: faa89be0ef86aebd6fd0a03eed23839c
summary: The Xorg Evdev Driver package contains a Generic Linux input driver for the
  Xorg X server. It handles keyboard, mouse, touchpads and wacom devices, though for
  touchpad and wacom advanced handling, additional drivers are required.
download_size: 344 KB
disk_space: 3.7 MB
sbu: less than 0.1 SBU
depends:
  required:
  - libevdev
  - mtdev
  - xorg-server
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 460000
