format: alps-port-v1
name: liblinear
version: '250'
page_kind: single_package
section: general
page: liblinear
title: liblinear-250
tarball: liblinear-250.tar.gz
url: https://github.com/cjlin1/liblinear/archive/v250/liblinear-250.tar.gz
md5: 53ffb394295c7f766adc200a603d6e0d
summary: This package provides a library for learning linear classifiers for large
  scale applications. It supports Support Vector Machines (SVM) with L2 and L1 loss,
  logistic regression, multi class classification and also Linear Programming Machines
  (L1-regularized SVMs). Its computational complexity scales linearly with the number
  of training examples making it one of the fastest SVM solvers around.
download_size: 76 KB
disk_space: 712 KB
sbu: less than 0.1 SBU
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 152000
