format: alps-port-v1
name: audacious
version: 4.6.1
page_kind: multi_package
section: multimedia
page: audacious
title: Audacious-4.6.1
tarball: audacious-4.6.1.tar.bz2
url: https://distfiles.audacious-media-player.org/audacious-4.6.1.tar.bz2
md5: aca871be9bcca924897060fe51ec87d5
summary: ''
download_size: 516 KB
disk_space: 16 MB (with GTK support)
sbu: 0.2 SBU (Using parallelism=4; with GTK support)
depends:
  required:
  - gtk
  - qt
  recommended:
  - libarchive
  - mpg123
  - ffmpeg
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 811000
