format: alps-port-v1
name: network-manager-applet
version: 1.34.0
page_kind: single_package
section: basicnet
page: network-manager-applet
title: network-manager-applet-1.34.0
tarball: network-manager-applet-1.34.0.tar.xz
url: https://download.gnome.org/sources/network-manager-applet/1.34/network-manager-applet-1.34.0.tar.xz
md5: 83ff059aff3a691766d5f0079209e5af
summary: The NetworkManager Applet provides a tool and a panel applet used to configure
  wired and wireless network connections through GUI. It's designed for use with any
  desktop environment that uses GTK+, such as Xfce and LXDE.
download_size: 1.9 MB
disk_space: 46 MB (with tests)
sbu: 0.4 SBU (with tests)
depends:
  required:
  - gtk
  - libnma
  - libsecret
  - polkit
  - polkit-authentication-agent
  recommended:
  - glib
  - modemmanager
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 384000
