format: alps-port-v1
name: libhandy
version: 1.8.3
page_kind: single_package
section: x
page: libhandy1
title: libhandy-1.8.3
tarball: libhandy-1.8.3.tar.xz
url: https://download.gnome.org/sources/libhandy/1.8/libhandy-1.8.3.tar.xz
md5: af586a91ff6d4093a6e7e283dfab5f7f
summary: The libhandy package provides additional GTK UI widgets for use in developing
  user interfaces.
download_size: 1.8 MB
disk_space: 24 MB (with tests)
sbu: 0.1 SBU (with tests)
depends:
  required:
  - gtk
  recommended:
  - vala
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 500000
