format: alps-port-v1
name: kunitconversion
version: 6.29.0
page_kind: kde_batch
section: kde
page: frameworks6
title: kunitconversion-6.29.0
tarball: kunitconversion-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/kunitconversion-6.29.0.tar.xz
md5: 1dbc1a568c3991bfd9c8780659c61558
summary: KDE batch package from frameworks6.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 27
book_order: 548028
