format: alps-port-v1
name: gitserver
version: '0'
page_kind: configuration
section: general
page: gitserver
title: Running a Git Server
tarball: ''
url: ''
md5: ''
summary: This section will describe how to set up, administer and secure a git server.
  Git has many options available. For more detailed documentation see https://git-scm.com/book/en/v2.
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units:
- git-daemon
provides: []
conflicts: []
book_order: 331000
