format: alps-port-v1
name: gnome-tweaks
version: '49.0'
page_kind: single_package
section: gnome
page: gnome-tweaks
title: gnome-tweaks-49.0
tarball: gnome-tweaks-49.0.tar.xz
url: https://download.gnome.org/sources/gnome-tweaks/49/gnome-tweaks-49.0.tar.xz
md5: 6c8dbfcefcc5dbab6605cc6f0df1ba62
summary: GNOME Tweaks is a simple program used to tweak advanced GNOME settings.
download_size: 680 KB
disk_space: 4.5 MB
sbu: less than 0.1 SBU
depends:
  required:
  - gtk
  - gsettings-desktop-schemas
  - libadwaita
  - libgudev
  - pygobject
  - sound-theme-freedesktop
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 620000
