format: alps-port-v1
name: dbusmock
version: 0.38.1
page_kind: python_module
section: general
page: python-modules
title: dbusmock-0.38.1
tarball: python_dbusmock-0.38.1.tar.gz
url: https://files.pythonhosted.org/packages/source/p/python-dbusmock/python_dbusmock-0.38.1.tar.gz
md5: e90b10618f5a0c7f5dcc4d4a56c6ce07
summary: dbusmock is a Python library useful for writing tests for software which
  talks to D-Bus services.
download_size: 108 KB
disk_space: 2.4 MB
sbu: less than 0.1 SBU
depends:
  required:
  - dbus-python
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 344000
