format: alps-port-v1
name: git
version: 2.55.0
page_kind: single_package
section: general
page: git
title: Git-2.55.0
tarball: git-2.55.0.tar.xz
url: https://www.kernel.org/pub/software/scm/git/git-2.55.0.tar.xz
md5: 758c02a1b621cc0868ee0a0d99573e6b
summary: 'Git is a free and open source, distributed version control system designed
  to handle everything from small to very large projects with speed and efficiency.
  Every Git clone is a full-fledged repository with complete history and full revision
  tracking capabilities, not dependent on network access or a central server. Branching
  and merging are fast and easy to do. Git is used for version control of '
download_size: 7.8 MB
disk_space: 403 MB (with tests and downloaded documentation; add 22 MB for building
  docs)
sbu: 0.4 SBU (add 2.0 SBU for tests (disk speed dependent) and 1.0 SBU for building
  docs (all with parallelism=4)
depends:
  required: []
  recommended:
  - curl
  - rustc
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 330000
