format: alps-port-v1
name: xdg-utils
version: 1.2.1
page_kind: single_package
section: xsoft
page: xdg-utils
title: xdg-utils-1.2.1
tarball: xdg-utils-v1.2.1.tar.gz
url: https://gitlab.freedesktop.org/xdg/xdg-utils/-/archive/v1.2.1/xdg-utils-v1.2.1.tar.gz
md5: 4c72585a98ba8f775cb9e72b066cc0df
summary: xdg-utils is a set of command line tools that assist applications with a
  variety of desktop integration tasks. It is required for Linux Standards Base (LSB)
  conformance.
download_size: 304 KB
disk_space: 3.3 MB (with tests)
sbu: 2.5 SBU (with tests)
depends:
  required:
  - xmlto
  - lynx
  - links
  - xorg-applications
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 742000
