format: alps-port-v1
name: pycairo
version: 1.29.1
page_kind: python_module
section: general
page: python-modules
title: PyCairo-1.29.1
tarball: pycairo-1.29.1.tar.gz
url: https://github.com/pygobject/pycairo/releases/download/v1.29.1/pycairo-1.29.1.tar.gz
md5: fc7c3b4104e88df7dea34af4314b9d12
summary: PyCairo provides Python bindings to Cairo.
download_size: 652 KB
disk_space: 5.0 MB
sbu: less than 0.1 SBU
depends:
  required:
  - cairo
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 344000
