format: alps-port-v1
name: plasma-integration
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: plasma-integration-6.7.4
tarball: plasma-integration-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/plasma-integration-6.7.4.tar.xz
md5: 270a34cd1483afba2295c18ee09c5da7
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 38
book_order: 578039
