format: alps-port-v1
name: meta-gnome
version: '1'
page_kind: meta
section: meta
page: meta-gnome
title: meta-gnome
tarball: ''
url: ''
md5: ''
summary: 'Meta-package: install BLFS ports from section ''gnome'''
depends:
  required: []
  recommended: []
  ignore_for_order: []
members:
- baobab
- brasero
- dconf-0.49.0-dconf-editor
- evince
- evolution
- evolution-data-server
- file-roller
- gcr
- geocode-glib
- gexiv2
- gjs
- gnome-autoar
- gnome-backgrounds
- gnome-bluetooth
- gnome-calculator
- gnome-color-manager
- gnome-connections
- gnome-control-center
- gnome-desktop
- gnome-disk-utility
- gnome-keyring
- gnome-logs
- gnome-maps
- gnome-menus
- gnome-nettool
- gnome-online-accounts
- gnome-power-manager
- gnome-session
- gnome-settings-daemon
- gnome-shell
- gnome-shell-extensions
- gnome-system-monitor
- gnome-terminal
- gnome-tweaks
- gnome-user-docs
- gnome-weather
- gsettings-desktop-schemas
- gsound
- gucharmap
- gvfs
- gweather-locations
- libgee
- libgtop
- libgweather
- libpeas
- librest
- libsecret
- libshumate
- localsearch
- loupe
- mutter
- nautilus
- seahorse
- showtime
- snapshot
- tecla
- tinysparql
- totem-pl-parser
- vte
- xdg-desktop-portal-gnome
- yelp
- yelp-xsl
bootscripts: []
provides: []
conflicts: []
book_order: 10001002
