format: alps-port-v1
name: meta-multimedia
version: '1'
page_kind: meta
section: meta
page: meta-multimedia
title: meta-multimedia
tarball: ''
url: ''
md5: ''
summary: 'Meta-package: install BLFS ports from section ''multimedia'''
depends:
  required: []
  recommended: []
  ignore_for_order: []
members:
- alsa-firmware
- alsa-lib
- alsa-plugins
- alsa-tools
- alsa-utils
- audacious
- audiofile
- cdparanoia-iii
- cdrdao
- cdrtools
- dav1d
- dvd+rw-tools
- faac
- faad2
- fdk-aac
- ffmpeg
- flac
- frei0r
- gavl
- gst-libav
- gst-plugins-bad
- gst-plugins-base
- gst-plugins-good
- gst-plugins-rs
- gst-plugins-ugly
- gstreamer
- id3lib
- intel-media-driver
- intel-vaapi-driver
- kwave
- lame
- liba52
- libao
- libaom
- libass
- libburn
- libcanberra
- libcddb
- libcdio
- libde265
- libdv
- libdvdcss
- libdvdnav
- libdvdread
- libisoburn
- libisofs
- libmad
- libmpeg2
- libmusicbrainz
- libogg
- libplacebo
- libsamplerate
- libsndfile
- libva
- libvorbis
- libvpx
- mlt
- mpg123
- mpv
- opus
- pavucontrol
- pipewire
- pnmixer
- pulseaudio
- sbc
- sdl2-compat
- sdl3
- sound-theme-freedesktop
- soundtouch
- speex
- svt-av1
- taglib
- v4l-utils
- vlc
- vorbis-tools
- wireplumber
- x264
- x265
- xine-lib
- xine-ui
- xvid
bootscripts: []
provides: []
conflicts: []
book_order: 10001535
