format: alps-port-v1
name: kapidox
version: 6.29.0
page_kind: kde_batch
section: kde
page: frameworks6
title: kapidox-6.29.0
tarball: kapidox-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/kapidox-6.29.0.tar.xz
md5: c1888280d30447724d491e688e03cf45
summary: KDE batch package from frameworks6.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 2
book_order: 548003
