format: alps-port-v1
name: phonon
version: 4.12.0
page_kind: single_package
section: kde
page: phonon
title: Phonon-4.12.0
tarball: phonon-4.12.0.tar.xz
url: https://download.kde.org/stable/phonon/4.12.0/phonon-4.12.0.tar.xz
md5: e80e9c73967080016bdb3c0ee514ceab
summary: Phonon is the multimedia API for KDE. It replaces the old aRts package. Phonon
  needs the VLC backend.
download_size: 400 KB
disk_space: 23 MB
sbu: 0.2 SBU (Using parallelism=4)
depends:
  required:
  - cmake
  - extra-cmake-modules
  - glib
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 541000
cycle_policy:
  install_before: []
