format: alps-port-v1
name: mlt
version: 7.40.0
page_kind: single_package
section: multimedia
page: mlt
title: MLT-7.40.0
tarball: mlt-7.40.0.tar.gz
url: https://github.com/mltframework/mlt/releases/download/v7.40.0/mlt-7.40.0.tar.gz
md5: 259266dc466af040f33a8019a82b9936
summary: The MLT package is the Media Lovin Toolkit. It is an open source multimedia
  framework, designed and developed for television broadcasting. It provides a toolkit
  for broadcasters, video editors, media players, transcoders, web streamers and many
  more types of applications.
download_size: 6.5 MB
disk_space: 49 MB
sbu: 0.2 SBU (Using parallelism=4)
depends:
  required:
  - cmake
  recommended:
  - ffmpeg
  - frei0r
  - libsamplerate
  - qt
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/mlt-7.40.0-ffmpeg-9.0.patch
  filename: mlt-7.40.0-ffmpeg-9.0.patch
book_order: 792000
