format: alps-port-v1
name: xfce-apps
version: '0'
page_kind: configuration
section: xfce
page: xfce-apps
title: Xfce Applications
tarball: ''
url: ''
md5: ''
summary: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
provides: []
conflicts: []
book_order: 665000
