format: alps-port-v1
name: glib
version: 2.88.3
page_kind: single_package
section: general
page: glib2
title: GLib-2.88.3
tarball: glib-2.88.3.tar.xz
url: https://download.gnome.org/sources/glib/2.88/glib-2.88.3.tar.xz
md5: b61c04cfbf55b0d24fbe64e4ac9e9d56
summary: The GLib package contains low-level libraries useful for providing data structure
  handling for C, portability wrappers and interfaces for runtime functionality such
  as an event loop, threads, dynamic loading and an object system.
download_size: 5.6 MB
disk_space: 430 MB (with tests and documentation)
sbu: 0.7 SBU (add 0.5 SBU for tests; both using parallelism=4)
depends:
  required: []
  recommended:
  - docutils
  - libxslt
  - shared-mime-info
  ignore_for_order:
  - shared-mime-info
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: Optional patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/glib-skip_warnings-1.patch
  filename: glib-skip_warnings-1.patch
- label: patch (from build commands)
  url: https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz
  filename: gobject-introspection-1.86.0.tar.xz
book_order: 117000
cycle_policy:
  install_before:
  - shared-mime-info
