format: alps-port-v1
name: libsigc++
version: 3.6.0
page_kind: single_package
section: general
page: libsigc3
title: libsigc++-3.6.0
tarball: libsigc++-3.6.0.tar.xz
url: https://download.gnome.org/sources/libsigc++/3.6/libsigc++-3.6.0.tar.xz
md5: b7205d5465ac15fbc0c781d39b4011be
summary: The libsigc++ package implements a typesafe callback system for standard
  C++. This version is part of a new API for supporting gtkmm-4.
download_size: 972 KB
disk_space: 12 MB (with tests)
sbu: 0.4 SBU (with tests)
depends:
  required: []
  recommended:
  - boost
  - libxslt
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 163000
