format: alps-port-v1
name: knighttime
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: knighttime-6.7.4
tarball: knighttime-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/knighttime-6.7.4.tar.xz
md5: b035d3a464916c60a21b8a57d0698612
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 12
book_order: 578013
