format: alps-port-v1
name: xdg-desktop-portal-gnome
version: '50.0'
page_kind: single_package
section: gnome
page: xdg-desktop-portal-gnome
title: xdg-desktop-portal-gnome-50.0
tarball: xdg-desktop-portal-gnome-50.0.tar.xz
url: https://download.gnome.org/sources/xdg-desktop-portal-gnome/50/xdg-desktop-portal-gnome-50.0.tar.xz
md5: 6ef350f31272babbb536cc745746adad
summary: xdg-desktop-portal-gnome is a backend for xdg-desktop-portal which uses GTK
  and various pieces of GNOME infrastructure.
download_size: 196 KB
disk_space: 11 MB
sbu: 0.2 SBU
depends:
  required:
  - gnome-desktop
  - gtk
  - libadwaita
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  recommended:
  - nautilus
  ignore_for_order:
  - nautilus
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 605000
cycle_policy:
  install_before:
  - nautilus
