format: alps-port-v1
name: ark
version: 26.04.3
page_kind: single_package
section: kde
page: ark
title: ark-26.04.3
tarball: ark-26.04.3.tar.xz
url: https://download.kde.org/stable/release-service/26.04.3/src/ark-26.04.3.tar.xz
md5: d716cf45066ca14705e7227267c31e08
summary: The Ark package is a KDE Frameworks-based Archive Manager. It is a graphical
  front end to tar, 7zip, UnRar, and other similar tools.
download_size: 2.9 MB
disk_space: 45 MB
sbu: 0.4 SBU (using parallelism=4)
depends:
  required:
  - kde-frameworks
  - libarchive
  recommended:
  - 7zip
  - cpio
  - unrar
  - zip
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 550000
