format: alps-port-v1
name: little-cms
version: 2.19.1
page_kind: single_package
section: general
page: lcms2
title: Little CMS-2.19.1
tarball: lcms2-2.19.1.tar.gz
url: https://github.com/mm2/Little-CMS/releases/download/lcms2.19.1/lcms2-2.19.1.tar.gz
md5: 541978f73749499e9e0277bfe5a3c868
summary: The Little Color Management System is a small-footprint color management
  engine, with special focus on accuracy and performance. It uses the International
  Color Consortium standard (ICC), which is the modern standard for color management.
download_size: 5.5 MB
disk_space: 17 MB (with the tests)
sbu: 0.2 SBU (with the tests)
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 224000
