format: alps-port-v1
name: advanced-network
version: '0'
page_kind: configuration
section: basicnet
page: advanced-network
title: Advanced Network Setup
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 365000
