format: alps-port-v1
name: evolution-data-server
version: 3.60.2
page_kind: single_package
section: gnome
page: evolution-data-server
title: evolution-data-server-3.60.2
tarball: evolution-data-server-3.60.2.tar.xz
url: https://download.gnome.org/sources/evolution-data-server/3.60/evolution-data-server-3.60.2.tar.xz
md5: 933c4804d9d2ba99f93fc26005282a3f
summary: The Evolution Data Server package provides a unified backend for programs
  that work with contacts, tasks, and calendar information. It was originally developed
  for Evolution (hence the name), but is now used by other packages as well.
download_size: 5.0 MB
disk_space: 150 (with tests)
sbu: 0.7 SBU (With tests; both using parallelism=4)
depends:
  required:
  - libical
  - libsecret
  - nss
  recommended:
  - gnome-online-accounts
  - glib
  - gtk
  - icu
  - libcanberra
  - libgweather
  - vala
  - webkitgtk
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 601000
