format: alps-port-v1
name: speex
version: 1.2.1
page_kind: multi_package
section: multimedia
page: speex
title: Speex-1.2.1
tarball: speex-1.2.1.tar.gz
url: https://downloads.xiph.org/releases/speex/speex-1.2.1.tar.gz
md5: fe7bf610883ff202092b92c72fe0fe3e
summary: Speex is an audio compression format designed specifically for speech. It
  is well-adapted to internet applications and provides useful features that are not
  present in most other CODECs.
download_size: 1020 KB
disk_space: 7.8 MB
sbu: less than 0.1 SBU
depends:
  required:
  - libogg
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: additional download
  url: https://downloads.xiph.org/releases/speex/speexdsp-1.2.1.tar.gz
  filename: speexdsp-1.2.1.tar.gz
  md5: e6eb5ddef743a362c8018f260b91dca5
book_order: 801000
