format: alps-port-v1
name: gtk-doc
version: 1.36.1
page_kind: single_package
section: general
page: gtk-doc
title: GTK-Doc-1.36.1
tarball: gtk-doc-1.36.1.tar.xz
url: https://download.gnome.org/sources/gtk-doc/1.36/gtk-doc-1.36.1.tar.xz
md5: 819b11aa730cf5108f1df3f0eec91cf9
summary: The GTK-Doc package contains a code documenter. This is useful for extracting
  specially formatted comments from the code to create API documentation. This package
  is optional; if it is not installed, packages will not build the documentation.
  This does not mean that you will not have any documentation. If GTK-Doc is not available,
  the install process will copy any pre-built documentation to your s
download_size: 584 KB
disk_space: 16 MB (add 2.2 MB for tests)
sbu: less than 0.1 SBU (with tests)
depends:
  required:
  - docbook-xml
  - docbook-xsl-nons
  - glib
  - itstool
  - libxslt
  - pygments
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 261000
