format: alps-port-v1
name: stunnel
version: '5.80'
page_kind: single_package
section: postlfs
page: stunnel
title: stunnel-5.80
tarball: stunnel-5.80.tar.gz
url: https://www.stunnel.org/downloads/archive/5.x/stunnel-5.80.tar.gz
md5: 751363a9ecc0f6bdfb1879c4d56c1567
summary: The stunnel package contains a program that allows you to encrypt arbitrary
  TCP connections inside SSL (Secure Sockets Layer) so you can easily communicate
  with clients over secure channels. stunnel can also be used to tunnel PPP over network
  sockets without changes to the server package source code.
download_size: 920 KB
disk_space: 12 MB
sbu: less than 0.1 SBU
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 62000
