format: alps-port-v1
name: lsof
version: 4.99.7
page_kind: single_package
section: general
page: lsof
title: lsof-4.99.7
tarball: lsof-4.99.7.tar.gz
url: https://github.com/lsof-org/lsof/releases/download/4.99.7/lsof-4.99.7.tar.gz
md5: 46647a774bb8ba630eb738c3aa1b5275
summary: The lsof package is useful to LiSt Open Files for a given running application
  or process.
download_size: 1.2 MB
disk_space: 14 MB (with tests)
sbu: 0.6 SBU (with tests)
depends:
  required:
  - libtirpc
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 267000
