format: alps-port-v1
name: ojdk-conf
version: '0'
page_kind: configuration
section: general
page: ojdk-conf
title: Configuring the Java environment
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 361000
