format: alps-port-v1
name: qca
version: 2.3.10
page_kind: single_package
section: general
page: qca
title: Qca-2.3.10
tarball: qca-2.3.10.tar.xz
url: https://download.kde.org/stable/qca/2.3.10/qca-2.3.10.tar.xz
md5: c3ed3262c83c43bdeb610836769b1534
summary: Qca aims to provide a straightforward and cross-platform crypto API, using
  Qt datatypes and conventions. Qca separates the API from the implementation, using
  plugins known as Providers.
download_size: 748 KB
disk_space: 56 MB (with tests)
sbu: 0.7 SBU (using parallelism=4; with tests)
depends:
  required:
  - make-ca
  - cmake
  - qt
  - which
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/qca-2.3.10-openssl4_fixes-1.patch
  filename: qca-2.3.10-openssl4_fixes-1.patch
book_order: 190000
