format: alps-port-v1
name: gdk-pixbuf
version: 2.44.7
page_kind: single_package
section: x
page: gdk-pixbuf
title: gdk-pixbuf-2.44.7
tarball: gdk-pixbuf-2.44.7.tar.xz
url: https://download.gnome.org/sources/gdk-pixbuf/2.44/gdk-pixbuf-2.44.7.tar.xz
md5: 2a12da2133476b7b36fbfcadd7133315
summary: The Gdk Pixbuf package is a toolkit for image loading and pixel buffer manipulation.
  It is used by GTK+ 3 to load and manipulate images. In the past it was distributed
  as part of GTK+ 2, but it was split off into a separate package in preparation for
  the change to GTK+ 3.
download_size: 5.8 MB
disk_space: 68 MB (with tests)
sbu: 0.2 SBU (with tests)
depends:
  required:
  - glib
  - shared-mime-info
  recommended:
  - docutils
  - glycin
  ignore_for_order:
  - glycin
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 480000
cycle_policy:
  install_before:
  - glycin
