format: alps-port-v1
name: lxqt-kconfig
version: 6.29.0
page_kind: single_package
section: lxqt
page: lxqt-kconfig
title: kconfig-6.29.0 for lxqt
tarball: kconfig-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/kconfig-6.29.0.tar.xz
md5: 194b8c40c5c7e143b44ee2f8dadae775
summary: The kconfig package provides access to configuration files.
download_size: 383 KB
disk_space: 29 MB
sbu: 0.2 SBU (Using parallelism=4)
depends:
  required:
  - extra-cmake-modules
  - qt
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 676000
