format: alps-port-v1
name: users
version: '0'
page_kind: configuration
section: postlfs
page: users
title: About System Users and Groups
tarball: ''
url: ''
md5: ''
summary: 'Throughout BLFS, many packages install programs that run as daemons or in
  some way should have a user or group name assigned. Generally these names are used
  to map a user ID (uid) or group ID (gid) for system use. Generally the specific
  uid or gid numbers used by these applications are not significant. The exception
  of course, is that root has a uid and gid of 0 (zero) that is indeed special. The '
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 33000
