format: alps-port-v1
name: bluez-qt
version: 6.29.0
page_kind: kde_batch
section: kde
page: frameworks6
title: bluez-qt-6.29.0
tarball: bluez-qt-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/bluez-qt-6.29.0.tar.xz
md5: c0ee97a3f6b78782eb378ca05a89a653
summary: KDE batch package from frameworks6.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - extra-cmake-modules
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 55
book_order: 548056
