format: alps-port-v1
name: goffice
version: 0.10.61
page_kind: single_package
section: x
page: goffice010
title: GOffice-0.10.61
tarball: goffice-0.10.61.tar.xz
url: https://download.gnome.org/sources/goffice/0.10/goffice-0.10.61.tar.xz
md5: a8477240f8c358bd0add4abca40e3208
summary: The GOffice package contains a library of GLib/GTK document centric objects
  and utilities. This is useful for performing common operations for document centric
  applications that are conceptually simple, but complex to implement fully. Some
  of the operations provided by the GOffice library include support for plugins, load/save
  routines for application documents and undo/redo functions.
download_size: 2.5 MB
disk_space: 83 MB (with tests)
sbu: 0.5 SBU (Using parallelism=4; with tests)
depends:
  required:
  - gtk
  - intltool
  - libgsf
  - librsvg
  - libxslt
  - which
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 484000
