format: alps-port-v1
name: kf6
version: '0'
page_kind: configuration
section: kde
page: kf6
title: KDE Frameworks 6
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 546000
