format: alps-port-v1
name: mit-kerberos-v5
version: 1.22.2
page_kind: single_package
section: postlfs
page: mitkrb
title: MIT Kerberos V5-1.22.2
tarball: krb5-1.22.2.tar.gz
url: https://kerberos.org/dist/krb5/1.22/krb5-1.22.2.tar.gz
md5: 42472b11771d074329e0cc776d2eb5fd
summary: MIT Kerberos V5 is a free implementation of Kerberos 5. Kerberos is a network
  authentication protocol. It centralizes the authentication database and uses kerberized
  applications to work with servers or services that support Kerberos allowing single
  logins and encrypted communication over internal networks or the Internet.
download_size: 8.4 MB
disk_space: 149 MB (with tests)
sbu: 0.4 SBU (Using parallelism=4; add 3.8 SBU for tests)
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units:
- krb5
provides: []
conflicts: []
patches:
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/mitkrb-1.22.2-upstream_fix-1.patch
  filename: mitkrb-1.22.2-upstream_fix-1.patch
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/mitkrb-1.22.2-security_fix-1.patch
  filename: mitkrb-1.22.2-security_fix-1.patch
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/mitkrb-1.22.2-openssl_4_fixes-1.patch
  filename: mitkrb-1.22.2-openssl_4_fixes-1.patch
book_order: 53000
