format: alps-port-v1
name: libgtop
version: 2.41.3
page_kind: single_package
section: gnome
page: libgtop
title: libgtop-2.41.3
tarball: libgtop-2.41.3.tar.xz
url: https://download.gnome.org/sources/libgtop/2.41/libgtop-2.41.3.tar.xz
md5: 465db9f4f695c298d9c48dcf7f32a9c0
summary: The libgtop package contains a library for accessing system performance data.
download_size: 740 KB
disk_space: 19 MB
sbu: 0.2 SBU
depends:
  required:
  - glib
  - xorg-libraries
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 596000
