format: alps-port-v1
name: kconfigwidgets
version: 6.29.0
page_kind: kde_batch
section: kde
page: frameworks6
title: kconfigwidgets-6.29.0
tarball: kconfigwidgets-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/kconfigwidgets-6.29.0.tar.xz
md5: 21d71db72c242423c2758c84e8d2ebfd
summary: KDE batch package from frameworks6.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - extra-cmake-modules
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 29
book_order: 548030
