format: alps-port-v1
name: vulkan-headers
version: 1.4.357.0
page_kind: single_package
section: x
page: vulkan-headers
title: Vulkan-Headers-1.4.357.0
tarball: Vulkan-Headers-vulkan-sdk-1.4.357.0.tar.gz
url: https://github.com/KhronosGroup/Vulkan-Headers/archive/vulkan-sdk-1.4.357.0/Vulkan-Headers-vulkan-sdk-1.4.357.0.tar.gz
md5: 64a23bb12e95a2017004d72569132929
summary: The Vulkan-Headers package contains a set of header files necessary to build
  and link applications against the Vulkan API.
download_size: 3.3 MB
disk_space: 122 MB
sbu: less than 0.1 SBU (with tests)
depends:
  required:
  - cmake
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 511000
