format: alps-port-v1
name: thunar
version: 4.20.9
page_kind: single_package
section: xfce
page: thunar
title: thunar-4.20.9
tarball: thunar-4.20.9.tar.bz2
url: https://archive.xfce.org/src/xfce/thunar/4.20/thunar-4.20.9.tar.bz2
md5: 7d6daadb0c241ebfaed2684950a67f74
summary: Thunar is the Xfce file manager, a GTK+ 3 GUI to organise the files on your
  computer.
download_size: 4.5 MB
disk_space: 86 MB
sbu: 0.2 SBU (Using parallelism=4)
depends:
  required:
  - exo
  - hicolor-icon-theme
  recommended:
  - libgudev
  - libnotify
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 656000
