format: alps-port-v1
name: redland
version: 1.0.17
page_kind: single_package
section: general
page: redland
title: Redland-1.0.17
tarball: redland-1.0.17.tar.gz
url: https://download.librdf.org/source/redland-1.0.17.tar.gz
md5: e5be03eda13ef68aabab6e42aa67715e
summary: Redland is a set of free software C libraries that provide support for the
  Resource Description Framework (RDF).
download_size: 1.6 MB
disk_space: 18 MB
sbu: 0.2 SBU
depends:
  required:
  - rasqal
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 303000
