format: alps-port-v1
name: datetime-format-builder
version: '0.83'
page_kind: perl_module
section: general
page: perl-modules
title: DateTime::Format::Builder-0.83
tarball: DateTime-Format-Builder-0.83.tar.gz
url: https://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.83.tar.gz
md5: aa41917ca9ad69b3898728ce9c2fb477
summary: DateTime::Format::Builder creates DateTime parser classes and objects.
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - datetime-format-strptime
  - params-validate
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 339000
