format: alps-port-v1
name: cairomm-1.0
version: 1.14.6
page_kind: single_package
section: x
page: cairomm-1.0
title: libcairomm-1.0 (cairomm-1.14.6)
tarball: cairomm-1.14.6.tar.xz
url: https://www.cairographics.org/releases/cairomm-1.14.6.tar.xz
md5: 634242bb797fb6e9d7cfae1a83474d11
summary: The libcairomm-1.0 package provides a C++ interface to Cairo.
download_size: 620 KB
disk_space: 12 MB (with tests)
sbu: less than 0.1 SBU (with tests)
depends:
  required:
  - cairo
  - libsigc++
  recommended:
  - boost
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 475000
