format: alps-port-v1
name: x7legacy
version: '0'
page_kind: x11_driver
section: x
page: x7legacy
title: Xorg Legacy
tarball: individual
url: https://www.x.org/pub/individual/
md5: ''
summary: Xorg's ancestor (X11R1, in 1987) at first only provided bitmap fonts, with
  a tool (bdftopcf) to assist in their installation. With the introduction of xorg-server-1.19.0
  and libXfont2 many people will not need them. There are still a few old packages
  which might require, or benefit from, these deprecated fonts and so the following
  packages are shown here.
download_size: 4.2 MB
disk_space: 30 MB
sbu: 0.3 SBU
depends:
  required:
  - xorg-fonts
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 468000
