format: alps-port-v1
name: x7legacy
version: '0'
page_kind: xorg_batch
section: x
page: x7legacy
title: Xorg Legacy
tarball: ''
url: https://www.x.org/pub/individual/
md5: ''
summary: Xorg's ancestor (X11R1, in 1987) at first only provided bitmap fonts, with
  a tool (bdftopcf) to assist in their installation. With the introduction of xorg-server-1.19.0
  and libXfont2 many people will not need them. There are still a few old packages
  which might require, or benefit from, these deprecated fonts and so the following
  packages are shown here.
download_size: 4.2 MB
disk_space: 30 MB
sbu: 0.3 SBU
depends:
  required:
  - x7font
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
sources:
- filename: bdftopcf-1.1.1.tar.xz
  md5: e09b61567ab4a4d534119bba24eddfb1
  url: https://www.x.org/pub/individual/util/bdftopcf-1.1.1.tar.xz
- filename: font-adobe-100dpi-1.0.4.tar.xz
  md5: 20239f6f99ac586f10360b0759f73361
  url: https://www.x.org/pub/individual/font/font-adobe-100dpi-1.0.4.tar.xz
- filename: font-adobe-75dpi-1.0.4.tar.xz
  md5: 2dc044f693ee8e0836f718c2699628b9
  url: https://www.x.org/pub/individual/font/font-adobe-75dpi-1.0.4.tar.xz
- filename: font-jis-misc-1.0.4.tar.xz
  md5: 2c939d5bd4609d8e284be9bef4b8b330
  url: https://www.x.org/pub/individual/font/font-jis-misc-1.0.4.tar.xz
- filename: font-daewoo-misc-1.0.4.tar.xz
  md5: 6300bc99a1e45fbbe6075b3de728c27f
  url: https://www.x.org/pub/individual/font/font-daewoo-misc-1.0.4.tar.xz
- filename: font-isas-misc-1.0.4.tar.xz
  md5: fe2c44307639062d07c6e9f75f4d6a13
  url: https://www.x.org/pub/individual/font/font-isas-misc-1.0.4.tar.xz
- filename: font-misc-misc-1.1.3.tar.xz
  md5: 145128c4b5f7820c974c8c5b9f6ffe94
  url: https://www.x.org/pub/individual/font/font-misc-misc-1.1.3.tar.xz
book_order: 468000
