format: alps-port-v1
name: certifi
version: 2026.6.17
page_kind: python_module
section: general
page: python-dependencies
title: certifi-2026.6.17
tarball: certifi-2026.6.17.tar.gz
url: https://files.pythonhosted.org/packages/source/c/certifi/certifi-2026.6.17.tar.gz
md5: 1af47cd1635599db1f2e598ae6c4d751
summary: The certifi module provides Mozilla’s carefully curated collection of Root
  Certificates for validating the trustworthiness of SSL certificates while verifying
  the identity of TLS hosts.
download_size: 132 KB
disk_space: 700 KB
sbu: less than 0.1 SBU
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 345000
