format: alps-port-v1
name: pytest
version: 9.1.1
page_kind: python_module
section: general
page: python-modules
title: Pytest-9.1.1
tarball: pytest-9.1.1.tar.gz
url: https://files.pythonhosted.org/packages/source/p/pytest/pytest-9.1.1.tar.gz
md5: 31f635913c0b1bce9438be52d44398a8
summary: The Pytest framework makes it easy to write small, readable tests, and can
  scale to support complex functional testing for applications and libraries.
download_size: 1.6 MB
disk_space: 49 MB (with tests)
sbu: 1.3 SBU (with tests)
depends:
  required:
  - iniconfig
  - pluggy
  - pygments
  recommended:
  - setuptools_scm
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 344000
