format: alps-port-v1
name: extra-cmake-modules
version: 6.29.0
page_kind: single_package
section: kde
page: extra-cmake-modules
title: Extra-CMake-Modules-6.29.0
tarball: extra-cmake-modules-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/extra-cmake-modules-6.29.0.tar.xz
md5: b3795f9b843a58746ca5461713c088d8
summary: The Extra CMake Modules package contains extra CMake modules used by KDE
  Frameworks and other packages.
download_size: 332 KB
disk_space: 11 MB
sbu: less than 0.1 SBU
depends:
  required:
  - cmake
  recommended:
  - qt
  ignore_for_order:
  - qt
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 540000
cycle_policy:
  install_before:
  - qt
