format: alps-port-v1
name: breeze
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: breeze-6.7.4
tarball: breeze-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/breeze-6.7.4.tar.xz
md5: b5684af3d9c5f65056ce4b64e0c59a3c
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 3
book_order: 578004
