format: alps-port-v1
name: datetime-locale
version: '1.45'
page_kind: perl_module
section: general
page: perl-deps
title: DateTime::Locale-1.45
tarball: DateTime-Locale-1.45.tar.gz
url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.45.tar.gz
md5: 0ba952412b4e013dd42894625ddb3c20
summary: DateTime::Locale provides localization support for DateTime-1.66.
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - dist-checkconflicts
  - file-sharedir
  - namespace-autoclean
  - params-validationcompiler
  recommended:
  - cpan-meta-check
  - ipc-system-simple
  - test-file-sharedir
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 340000
