format: alps-port-v1
name: server
version: '0'
page_kind: configuration
section: server
page: server
title: Servers
tarball: ''
url: ''
md5: ''
summary: ''
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 421000
