format: alps-port-v1
name: xorg7
version: '0'
page_kind: configuration
section: x
page: xorg7
title: Introduction to Xorg-7
tarball: ''
url: ''
md5: ''
summary: Xorg is a freely redistributable, open-source implementation of the X Window
  System. This system provides a client/server interface between display hardware
  (the mouse, keyboard, and video displays) and the desktop environment, while also
  providing both the windowing infrastructure and a standardized application interface
  (API).
download_size: ''
disk_space: ''
sbu: ''
depends:
  required: []
  recommended: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 440000
