format: alps-port-v1
name: kwin
version: 6.7.4
page_kind: kde_batch
section: kde
page: plasma-all
title: kwin-6.7.4
tarball: kwin-6.7.4.tar.xz
url: https://download.kde.org/stable/plasma/6.7.4/kwin-6.7.4.tar.xz
md5: b5b51b6b7568329a8cf1190bdeba6e4a
summary: KDE batch package from plasma-all.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - extra-cmake-modules
  - qt
  - meta-frameworks6
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 14
book_order: 578015
