format: alps-port-v1
name: kconfig
version: 6.29.0
page_kind: kde_batch
section: kde
page: frameworks6
title: kconfig-6.29.0
tarball: kconfig-6.29.0.tar.xz
url: https://download.kde.org/stable/frameworks/6.29/kconfig-6.29.0.tar.xz
md5: 194b8c40c5c7e143b44ee2f8dadae775
summary: KDE batch package from frameworks6.html
download_size: ''
disk_space: ''
sbu: ''
depends:
  required:
  - extra-cmake-modules
  - qt
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
batch_index: 5
book_order: 548006
