format: alps-port-v1
name: epiphany
version: '50.5'
page_kind: single_package
section: xsoft
page: epiphany
title: Epiphany-50.5
tarball: epiphany-50.5.tar.xz
url: https://download.gnome.org/sources/epiphany/50/epiphany-50.5.tar.xz
md5: 1924ebe78616d8d3b9c2d44e5d862a34
summary: Epiphany is a simple yet powerful GNOME web browser targeted at non-technical
  users. Its principles are simplicity and standards compliance.
download_size: 4.4 MB
disk_space: 101 MB (with tests)
sbu: 0.2 SBU (with tests; both using parallelism=4)
depends:
  required:
  - blueprint-compiler
  - gcr
  - gnome-desktop
  - iso-codes
  - json-glib
  - libadwaita
  - libportal
  - nettle
  - webkitgtk
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 725000
