format: alps-port-v1
name: liboauth
version: 1.0.3
page_kind: single_package
section: postlfs
page: liboauth
title: liboauth-1.0.3
tarball: liboauth-1.0.3.tar.gz
url: https://downloads.sourceforge.net/liboauth/liboauth-1.0.3.tar.gz
md5: 689b46c2b3ab1a39735ac33f714c4f7f
summary: liboauth is a collection of POSIX-C functions implementing the OAuth Core
  RFC 5849 standard. Liboauth provides functions to escape and encode parameters according
  to OAuth specification and offers high-level functionality to sign requests or verify
  OAuth signatures as well as perform HTTP requests.
download_size: 496 KB
disk_space: 3.5 MB
sbu: less than 0.1 SBU
depends:
  required:
  - curl
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
patches:
- label: Required patch
  url: https://www.linuxfromscratch.org/patches/blfs/svn/liboauth-1.0.3-openssl-1.1.0-3.patch
  filename: liboauth-1.0.3-openssl-1.1.0-3.patch
book_order: 51000
