format: alps-port-v1
name: ncftp
version: 3.3.0
page_kind: single_package
section: basicnet
page: ncftp
title: NcFTP-3.3.0
tarball: ncftp-3.3.0-src.tar.gz
url: https://www.ncftp.com/public_ftp/ncftp/ncftp-3.3.0-src.tar.gz
md5: 43056719c50cae2ed6b614e20c86d37e
summary: The NcFTP package contains a powerful and flexible interface to the Internet
  standard File Transfer Protocol. It is intended to replace or supplement the stock
  ftp program.
download_size: 628 KB
disk_space: 13 MB
sbu: 0.2 SBU
depends:
  required: []
  recommended: []
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 368000
