format: alps-port-v1
name: gtk-vnc
version: 1.5.0
page_kind: single_package
section: x
page: gtk-vnc
title: gtk-vnc-1.5.0
tarball: gtk-vnc-1.5.0.tar.xz
url: https://download.gnome.org/sources/gtk-vnc/1.5/gtk-vnc-1.5.0.tar.xz
md5: 6e9815e7960636e95f626a3f164eb01d
summary: The Gtk VNC package contains a VNC viewer widget for GTK+. It is built using
  coroutines allowing it to be completely asynchronous while remaining single threaded.
download_size: 224 KB
disk_space: 11 MB
sbu: 0.2 SBU
depends:
  required:
  - gnutls
  - gtk
  - libgcrypt
  recommended:
  - glib
  - vala
  - pulseaudio
  ignore_for_order: []
bootscripts: []
systemd_units: []
provides: []
conflicts: []
book_order: 490000
